### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by gbiscuolo** [Crashedmind/PlayingWithPlantUMLSource#6]
Please can you add a license to this project?

Reading the [Open Source - The Network Effect](https://crashedmind.github.io/PlantUMLHitchhikersGuide/about/AboutThisGuide.html#open-source-the-network-effect) chapter I understand you would like this guide to be grown by the PlantUML community, for this reason I suggest the best license for this guide is the CC-BY-SA (not NC nor ND please).

Thanks for your work!
Giovanni

**Comment by Crashedmind** [comment]
thanks Giovanni - done - https://github.com/Crashedmind/PlayingWithPlantUMLSource/blob/master/README.md

**Comment by gbiscuolo** [comment]
Crashedmind ***@***.***> writes:

> thanks Giovanni - done - https://github.com/Crashedmind/PlayingWithPlantUMLSource/blob/master/README.md

LOL!  Thank you very much.

Ciao, Giovanni

-- 
380° (Giovanni Biscuolo public alter ego)

«Noi, incompetenti come siamo,
 non abbiamo alcun titolo per suggerire alcunché»

Disinformation flourishes because many people care deeply about injustice
but very few check the facts.  Ask me about <https://stallmansupport.org>.
